
import { useParams } from 'react-router-dom';
import Image1 from "../assets/articles-img/article-1.jpeg";
import Image2 from "../assets/articles-img/article-2.jpeg";
import Image3 from "../assets/articles-img/article-3.jpeg";
import Navbar from "../components/Navbar";

const articleData = {
  1: {
    id: 1,
    image: Image1,
    title: 'New Indonesian Law Affects Tax Regulations',
    date: 'September 18, 2023',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.',
  },
  2: {
    id: 2,
    image: Image2,
    title: 'Changes in Environmental Regulations in Indonesia',
    date: 'September 17, 2023',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.',
  },
  3: {
    id: 3,
    image: Image3,
    title: "New Data Privacy Regulations in Indonesia",
    date: "September 16, 2023",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.",
  },
  4: {
    id: 4,
    image: Image2,
    title: "Indonesian Government Announces Trade Policy Changes",
    date: "September 15, 2023",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.",
  },
  5: {
    id: 5,
    image: Image1,
    title: "Legal Implications of Technology Advancements in Indonesia",
    date: "September 14, 2023",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.",
  },
  6:  {
    id: 6,
    image: Image2,
    title: "New Intellectual Property Laws in Indonesia",
    date: "September 13, 2023",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.",
  },
  7:{
    id: 7,
    image: Image1,
    title: "Recent Environmental Lawsuits in Indonesia",
    date: "September 12, 2023",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.",
  },
  8: {
    id: 8,
    image: Image2,
    title: "Challenges in Contract Law for Indonesian Businesses",
    date: "September 11, 2023",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.",
  },
  9: {
    id: 9,
    image: Image1,
    title: "Impact of Labor Law Reforms in Indonesia",
    date: "September 10, 2023",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.",
  },
  10: {
    id: 10,
    image: Image2,
    title: "New Regulations for Foreign Investments in Indonesia",
    date: "September 9, 2023",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eleifend euismod dolor in rutrum. Donec viverra, dolor at aliquam auctor, purus risus ornare orci, et lobortis lacus magna vel justo. Morbi libero lorem, sodales tincidunt ligula sit amet, tincidunt pretium ligula. Vivamus eu lacinia magna. Fusce purus dolor, maximus non orci sed, dapibus ultrices justo. Pellentesque scelerisque placerat ligula, ac hendrerit sapien interdum sit amet. Cras mollis mi purus, eu viverra metus fringilla vel. Praesent at volutpat libero. Proin mattis vestibulum pulvinar. Mauris eu nunc erat. Nullam non massa ut orci faucibus ullamcorper. Nullam rutrum, magna sed mollis suscipit, ipsum magna semper ex, nec mattis nisi massa non dolor. Nullam tristique nec lacus non dapibus. Mauris eget augue tristique, laoreet orci eu, pellentesque nibh. Aenean nec convallis tellus. Duis tristique laoreet venenatis. Nulla scelerisque placerat quam, sit amet lobortis orci semper eu. Donec auctor ut augue et congue. Vestibulum sapien diam, gravida vel nisi vitae, lacinia sagittis ligula. Integer mollis congue ligula, eget elementum ante ultrices lacinia. Praesent ut massa non mauris interdum ullamcorper non lacinia velit. Quisque rutrum porta accumsan. Vivamus nibh sapien, gravida quis ante et, pulvinar tempor leo.Aliquam erat volutpat. In dui lorem, eleifend eget leo sit amet, mollis rutrum quam. Vivamus aliquet mattis auctor. Sed at fringilla felis. Duis aliquam lacus metus, pulvinar faucibus mi mattis at. Sed nunc nulla, semper nec feugiat accumsan, dignissim ultricies augue. Nunc finibus diam nec magna placerat, sit amet hendrerit odio semper. Nunc rhoncus metus leo, quis rhoncus ligula hendrerit eget. Praesent hendrerit placerat orci eu tincidunt. Donec molestie ex turpis, eget pharetra lectus accumsan in. Proin dictum arcu a nunc convallis ultricies. Ut vel lacus ex. Mauris sit amet sapien nunc. Etiam at ligula nec sapien facilisis rhoncus nec id leo. Phasellus accumsan mauris in lectus volutpat imperdiet. Pellentesque viverra justo sit amet nunc pellentesque, et mattis elit dictum. Nam eu quam commodo, dignissim odio eget, aliquam purus. In nec magna interdum, interdum dolor et, fringilla nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed placerat lectus ante, ut lacinia metus mattis eget. In hac habitasse platea dictumst. Nunc dignissim, est sed porta tempus, orci mauris sodales mauris, a ultrices magna ante vitae neque. Cras fringilla faucibus nibh id mollis. Sed eleifend nibh libero, et tincidunt turpis aliquam et. Mauris vulputate, odio ut molestie imperdiet, velit magna ornare arcu, non efficitur arcu ex ut eros. Mauris eu dictum libero, sit amet ornare magna. Aenean sodales vulputate sem, vel iaculis sem pellentesque scelerisque.",
  },
};

function NewsArticle() {
  const { id } = useParams();

  const selectedArticle = articleData[id];

  if (!selectedArticle) {
    return <div>Article not found</div>;
  }

  return (
    <>
      <Navbar />
      <div className="container mx-auto px-4 lg:px-96 py-6">
        <img
          src={selectedArticle.image}
          alt="Article Banner"
          className="mx-auto mb-4 lg:max-w-2xl"
        />
        <h1 className="text-2xl font-semibold">{selectedArticle.title}</h1>
        <p className="text-gray-600">Date: {selectedArticle.date}</p>
        <p className="text-justify">{selectedArticle.content}</p>
      </div>
    </>
  
  
  );
}

export default NewsArticle;
